sonar.organization=alexander-trishin
sonar.projectKey=alexander-trishin_personal-website

sonar.projectName=Personal Website
sonar.projectVersion=1.1.0

sonar.sources=source
sonar.exclusions=source/index.tsx

sonar.tests=source
sonar.test.inclusions=source/**/*.test.ts,source/**/*.test.tsx
sonar.test.exclusions=source/index.tsx

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml

sonar.sourceEncoding=UTF-8
