name: Feature request 💄
description: Suggest a new idea.
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: Thanks for contributing by creating an issue! ❤️ Please provide a searchable summary of the issue in the title above ⬆️.
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: Describe how it should work.
  - type: textarea
    attributes:
      label: Motivation
      description: What are you trying to accomplish? Providing context helps us come up with a solution that is more useful in the real world.
