name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-unit-tests:
    name: Run tests / unit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --immutable

      - name: Run tests
        run: yarn test

  run-e2e-tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest] # Windows tests are supported, but they run too slow
        #os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            playwright-cache-folder: "~/.cache/ms-playwright"
          - os: macos-latest
            playwright-cache-folder: "~/Library/Caches/ms-playwright"
    #     - os: windows-latest
    #       playwright-cache-folder: '%USERPROFILE%\AppData\Local\ms-playwright'

    name: Run tests / e2e / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Get playwright version json
        id: playwright-version
        run: echo "json=$(yarn info @playwright/test --json)" >> $GITHUB_OUTPUT

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ${{ matrix.playwright-cache-folder }}
          key: ${{ runner.os }}-playwright-${{ fromJson(steps.playwright-version.outputs.json).children.Version }}
          restore-keys: ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: yarn --immutable

      - name: Install playwright dependencies
        run: yarn playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Install playwright dependencies (runtime only)
        run: yarn playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'

      - name: Run type check
        run: yarn typecheck

      - name: Run lint check
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Run playwright tests
        run: yarn test:e2e

      - name: Upload playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/${{ matrix.os }}/
          retention-days: 3
